### ISSUE TITLE
De finisat odată morda la ruby.debian.md

### ISSUE THREAD

**Issue by vitaliel** [ruby-moldova/rug-moldova-site#1]
Bună dimineața Ivan,

Facem presiune publică ;-)

Tu ai sau vei avea studenți pe care poți să-i îndrumi cu această sarcină.

Un gospodar adevărat (sau om adult) se ține de promisiuni! Și deja n-ai ce face, ți-ai luat responsabilitatea [atunci](https://plus.google.com/events/c4u9h8tdpukq059jj21m42sjim0) cu un așa entuziasm, e păcat să rămână doar vorbe. Și e treabă de o oră maxim, dar atâta energie scurge din tine de mult timp.

Spor la muncă și succese, sper să vii cu o estimare la comunitate pentru acest prim, sper că nu ultim task. :P

**Comment by minivan** [comment]
Dap' parcă este. Adică eu hz ce să mai adaug. Nişte feedback?

**Comment by minivan** [comment]
https://github.com/ruby-moldova/rug-site-build 

Poate cineva să arunce asta undeva? E static, nimic special.

**Comment by minivan** [comment]
Ah, nu, am văzut că nu lucrează bine. Trebuie să văd cioza trouble cu sassul.

**Comment by vitaliel** [comment]
Am pus online http://ruby.debian.md

**Comment by vitaliel** [comment]
@minivan 

când vezi problema cu sassul?
